In [23]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import math

In [37]:
def gen_random(x1, x2, N, mediana, media): 
    arr1 = np.random.randint(x1, mediana, int(N/2))
    arr2 = np.random.randint(mediana, x2, int(N/2))
    mid = [mediana]
    if(N%2==0):
        extra = 1
    else:
        extra = 0
    i = ((np.sum(arr1 + arr2) + mediana) - (media * (N+extra))) / x2
    decm, intg = math.modf(i)
    args = np.argsort(arr2)
    arr2[args[-x2-1:-1]] -= int(intg)
    arr2[args[-1]] -= int(np.round(decm * x2))
    return np.concatenate((arr1, mid, arr2))

In [41]:
for i in range(10):
    arr = gen_random(20,80,7,58,55)
    print(np.median(arr))
    print(arr.mean())
    print(arr)
    print()

56.0
55.0
[50 45 56 58 58 69 49]

58.0
55.0
[ 21  24  20  58  61  58 143]

58.0
55.0
[46 49 31 58 60 81 60]

58.0
55.0
[ 33  24  29  58  62 115  64]

57.0
55.0
[57 54 54 58 72 31 59]

58.0
55.0
[43 24 29 58 85 76 70]

58.0
55.0
[25 41 45 58 89 64 63]

51.0
55.0
[51 50 45 58 62 68 51]

58.0
55.0
[48 54 25 58 62 59 79]

58.0
55.0
[ 24  35  32  58  65  61 110]

