In [12]:
import numpy as np

a = np.zeros((5,5));
print(a)

for i in range(5):
    for j in range(5):
        a[i,j] = i*2;
print(a)
idx = slice(1,2)
print(idx)
print(a[idx])

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [2. 2. 2. 2. 2.]
 [4. 4. 4. 4. 4.]
 [6. 6. 6. 6. 6.]
 [8. 8. 8. 8. 8.]]
slice(1, 2, None)
[[2. 2. 2. 2. 2.]]
[[0. 2. 4. 6. 8.]]
